### ISSUE TITLE
Pop OS! Issues

### ISSUE THREAD

**Issue by ZayRTun** [EliverLara/Nordic#68]
Hi, I am really loving the Nordic theme on Pop OS. I have been using it for a while now. But recently I upgraded to Pop OS 20.04 and now I think there are some bugs. **Some dropdowns backgrounds
![Screenshot from 2020-05-04 09-23-55](https://user-images.githubusercontent.com/31787822/80933431-bb731800-8de9-11ea-8320-aca071b6e446.png)
 are white ** and Gnome Tweaks title bar goes all black for sometimes and may also return back to normal. It's like it is twitchy. Please check the screenshots below and I am using the `Nordic` theme.
![Screenshot from 2020-05-04 09-19-39](https://user-images.githubusercontent.com/31787822/80933335-528ba000-8de9-11ea-83f4-909cb601a2c7.png)

**Comment by EliverLara** [comment]
Hi, the gnome-tweaks issue seems to be a problem of the program itself as it occurs even with the default adwaita theme:

![Captura de pantalla de 2020-05-04 14-01-48](https://user-images.githubusercontent.com/9838260/81006108-934cde80-8e14-11ea-843e-4b4a2d677588.png)

The shell theme shown in your screenshot does not correspond to the Nordic theme, so please make sure you have installed and applied it correctly.

**Comment by azzarello** [comment]
So I have the shell theme extension installed and this theme applied for gnome shell as well, but there is another minor bug on the top bar. 
Most things look good, but the main pop_os notification panel has some weird visual bugs (photo attached). Is it possible to change the theme's font's by chance? Not a huge fan of the font shown in the top bar.
![image](https://user-images.githubusercontent.com/10367472/81096647-964eda00-8ebb-11ea-98fc-d42c92e977d5.png)

**Comment by lawzava** [comment]
Facing same issue. Basically shell just restarts to the default "Pop" after the restart. Doesn't matter if it's set through gnome-tweaks or through gsettings.

**Comment by EliverLara** [comment]
@azzarello that was fixed since 9f7be36, I just released a new version containing those changes.

**Comment by EliverLara** [comment]
@lawzava Does that only happen with the Nordic theme?

**Comment by lawzava** [comment]
@EliverLara so far I have noticed this behavior only with the Nordic theme. Although I've tried only 5-6 non-default ones.

**Comment by lawzava** [comment]
@EliverLara I have just tested the new version that was released few hours ago, the issue still persists. After log out/log in it goes back into using default theme shell. Although in tweaks it shows "Nordic-darker" (forgot to mention, I'm using Nordic Darker). Setting the shell to any other and then back to Nordic fixes the issue until the next log out.

**Comment by vancanhuit** [comment]
Thank you so much for creating such a beautiful theme. I've installed the latest release of the Nordic Darker theme on Pop!_OS 20.04 and the dropdown background is still white.
![Screenshot from 2020-06-14 15-37-46](https://user-images.githubusercontent.com/18382438/84588882-33a31380-ae55-11ea-9f67-61a47c27fe17.png)

Everything else OK so far.

**Comment by JnsDornbusch** [comment]
@vancanhuit you need to install the Gnome Extension [User Themes](https://extensions.gnome.org/extension/19/user-themes/) to customize the shell.
Simply select your Nordic Theme afterwards.

@EliverLara the problem has been fixed for me for weeks.
Guess we can close the issue now.

**Comment by vancanhuit** [comment]
Thanks @JnsDornbusch for pointing me out. So far looks good. But a small fix I want to do that is how to change the hour text above the temperature in gnome weather in `gnome-shell.css` file.

![Screenshot from 2020-06-14 16-56-08](https://user-images.githubusercontent.com/18382438/84590421-9817a000-ae60-11ea-8f36-bf388dc95212.png)

**Comment by JnsDornbusch** [comment]
@vancanhuit your Problem has been fixed on the next day by EliverLara.
![Screenshot from 2020-06-20 11-58-10](https://user-images.githubusercontent.com/22532095/85199175-d04e3100-b2ed-11ea-90bb-b8cb20479e21.png)

It was fixed by the commit of: 1e0b376f88e639c66164f34d3534240a1295c00d.

To alternate the color of the hour text simply edit the color line in gnome-shell/gnome-shell.css:
``` SCSS
.weather-button .weather-forecast-time {
  color: #b7c2d7;
  font-feature-settings: "tnum";
  font-weight: normal;
  padding-top: 0.2em;
  padding-bottom: 0.4em; }
```

**Comment by vancanhuit** [comment]
@JnsDornbusch Thank you so much.
